### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by hasan-sayeed** [lamalab-org/matextract-book#119] opened 2024-08-01 01:21 UTC
Hi all,

Great work! I'm going through the paper and was trying to run the notebooks on my machine. For some reason I was not able to install the dependencies following instructions from [here](https://matextract.pub/index.html). I'm getting the following error while trying step 3. 

I'm running this on a Windows 11 machine. Seems like uvloop doesn't support Windows. Is there any way to get around that?

```
error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\hsayeed\miniconda3\envs\text_to_insight_book_8\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\hsayeed\miniconda3\envs\text_to_insight_book_8\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hsayeed\miniconda3\envs\text_to_insight_book_8\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hsayeed\AppData\Local\Temp\pip-build-env-ui2_p946\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hsayeed\AppData\Local\Temp\pip-build-env-ui2_p946\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\hsayeed\AppData\Local\Temp\pip-build-env-ui2_p946\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.```

**Comment by kjappelbaum** [comment] 2024-08-01 07:09
Thanks for the report, I think it is caused by the dependency updates that I did and also caused #118. I'll give it a look

**Comment by kjappelbaum** [comment] 2024-08-01 07:18
I now dropped the last two dependency updates and the installation works again on GitHub (https://github.com/lamalab-org/matextract-book/actions/runs/10193759745/job/28198981323), but I'll now also verify locally

**Comment by kjappelbaum** [comment] 2024-08-01 07:27
And - then there is a different problem with the operating system. 
A quick fix would be to use WSL on Windows. I'll check if we can also remove `uvloop`

**Comment by kjappelbaum** [comment] 2024-08-01 10:52
@hasan-sayeed can you check after the latest updates? We now also did some checks on Windows and it seems to work on our side

**Comment by kjappelbaum** [comment] 2024-08-01 16:31
Awesome, thanks for confirming! I'll now close this issue, but feel free to re-open it if you run into something like this again!

Thanks also for trying the notebooks in the first place!

**Closed by kjappelbaum** 2024-08-01 16:31 UTC
